version: '3.8'

volumes:
  webdav_metadata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/webdav-mount
  seaweedfs_data:

services:
  # 1. rclone: Mounts the WebDAV share for the filer's metadata
  rclone-mount:
    image: rclone/rclone:latest
    container_name: seaweedfs-rclone-mount
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./rclone.conf:/config/rclone/rclone.conf:ro
      - webdav_metadata:/mnt/webdav:shared
    command: >
      mount webdav-remote: /mnt/webdav
      --allow-other
      --vfs-cache-mode writes
      --log-level INFO
    networks:
      - seaweedfs-net

  # 2. SeaweedFS Master: Coordinates the cluster
  seaweedfs-master:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-master
    restart: unless-stopped
    ports:
      - "9333:9333" # Master API
      - "19333:19333" # Master metrics
    command: master
    networks:
      - seaweedfs-net

  # 3. SeaweedFS Volume: Stores the actual file data
  seaweedfs-volume:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-volume
    restart: unless-stopped
    depends_on:
      - seaweedfs-master
    ports:
      - "8080:8080" # Volume server API
      - "18080:18080" # Volume server metrics
    volumes:
      - seaweedfs_data:/data
    command: volume -mserver="seaweedfs-master:9333" -port=8080
    networks:
      - seaweedfs-net

  # 4. SeaweedFS Filer: Manages metadata, stored on the WebDAV mount
  seaweedfs-filer:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-filer
    restart: unless-stopped
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
      - rclone-mount
    ports:
      - "8888:8888" # Filer API
      - "18888:18888" # Filer metrics
    volumes:
      - webdav_metadata:/data
      - ./config/filer.toml:/etc/seaweedfs/filer.toml
    command: filer -master="seaweedfs-master:9333"
    networks:
      - seaweedfs-net

  # 5. SeaweedFS S3 Gateway: Exposes the filer via S3 API
  seaweedfs-s3:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-s3-gateway
    restart: unless-stopped
    depends_on:
      - seaweedfs-filer
    ports:
      - "8333:8333" # S3 API port
    command: s3 -filer="seaweedfs-filer:8888" -domainName=${S3_DOMAIN_NAME}
    networks:
      - seaweedfs-net

networks:
  seaweedfs-net:
    name: seaweedfs-solution-net
