version: '3.8'

services:
  rclone-proxy:
    image: rclone/rclone:latest
    container_name: rclone-s3-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./rclone.conf:/config/rclone/rclone.conf:ro
    env_file: .env
    restart: unless-stopped
    command: >
      serve s3 webdav-remote:
      --addr :8080
      --s3-no-check-bucket
      --s3-no-head
      --stats 1m
      --log-level INFO
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
