# This is an EXAMPLE file.
# It is recommended to create the Secret manually for better security:
# kubectl create secret generic s3-credentials --from-literal=... -n rclone-proxy

apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: rclone-proxy
type: Opaque
data:
  # The values here are base64-encoded placeholders.
  # For example, `echo -n "YOUR_S3_ACCESS_KEY_ID" | base64`
  S3_ACCESS_KEY_ID: WU9VUl9TM19BQ0NFU1NfS0VZX0lE
  # For example, `echo -n "YOUR_S3_SECRET_ACCESS_KEY" | base64`
  S3_SECRET_ACCESS_KEY: WU9VUl9TM19TRUNSRVRfQUNDRVNTX0tFWQ==
